# yaml-language-server: $schema=./bootc-ci.schema.json
# {{ $owner := "Zeglius" }}
# {{ $image_name := "mybazzite" }}
# {{ $repo := printf "https://github.com/%s/%s" $owner $image_name }}

jobs:
  - containerfile: '{{ block "containerfile" . }}Containerfile{{ end }}'
    output-name: '{{ block "output_name" . }}ghcr.io/zeglius/mybazzite{{ end }}'
    output-tags:
      - latest
      - "{{ nowTag }}"
    build-args:
      BASE_IMAGE: ghcr.io/ublue-os/bazzite-nvidia:latest
    labels:
      io.artifacthub.package.keywords: bootc,ublue,universal-blue
      io.artifacthub.package.license: Apache-2.0
      org.opencontainers.image.title: '{{ template "output_name" . }}'
      org.opencontainers.image.source: '{{ $repo -}}/blob/main/{{- template "containerfile" . }}'
      org.opencontainers.image.url: "{{ $repo }}"
      org.opencontainers.image.version: "{{ nowTag }}"
      org.opencontainers.image.vendor: "{{ $owner }}"
