# yaml-language-server: $schema=./bootc-ci.schema.json
# {{ $owner := "Zeglius" }}
# {{ $image_name := "mybazzite" }}
# {{ $repo := printf "https://github.com/%s/%s" $owner $image_name }}
# {{ $now := nowTag }}

jobs:
  - containerfile: "Containerfile"
    # {{ $output_name := printf "ghcr.io/%s/%s" (lower $owner) $image_name }}
    output-name: "{{ $output_name }}"

    build-args:
      # {{ $image_base := "ghcr.io/ublue-os/bazzite-nvidia:latest" }}
      BASE_IMAGE: "{{ $image_base }}"

    # {{ $osInfo := $image_base | osRelease }}
    output-tags:
      - "{{ $now }}"
      - "{{ $osInfo.VERSION_ID }}"
      # {{ range $_, $tag := (slice "latest" "stable") }}
      - "{{ $tag }}"
      - "{{ $tag }}-{{ $osInfo.VERSION_ID }}"
      - "{{ $osInfo.VERSION_ID }}-{{ $tag }}"
      - "{{ $osInfo.VERSION_ID }}.{{ $now }}"
      - "{{ $tag }}-{{ $osInfo.VERSION_ID }}"
      - "{{ $tag }}-{{ $osInfo.VERSION_ID }}.{{ $now }}"
      # {{ else }}
      - latest
      # {{ end }}

    labels:
      io.artifacthub.package.keywords: bootc,ublue,universal-blue
      io.artifacthub.package.license: Apache-2.0
      org.opencontainers.image.title: "{{ $output_name }}"
      org.opencontainers.image.source: "{{ $repo }}/blob/main/Containerfile"
      org.opencontainers.image.url: "{{ $repo }}"
      org.opencontainers.image.version: "{{ $now }}"
      org.opencontainers.image.vendor: "{{ $owner }}"
