# yaml-language-server: $schema=./bootc-ci.schema.json
# {{ $secrets := default (dict) .secrets }}

# {{/* This block is for common inputs, like owner and image name */}}
# {{ $owner := "Zeglius" }}
# {{ $image_name := "mybazzite" }}
# {{ $major_version := default "42" $secrets.MAJOR_VERSION }}

# {{ $repo := printf "https://github.com/%s/%s" $owner $image_name }}
# {{ $now := nowTag }}

jobs:
  # {{ $output_name := printf "ghcr.io/%s/%s" (lower $owner) $image_name }}
  # {{ $image_base := printf "ghcr.io/ublue-os/bazzite-nvidia:%s" $major_version }}
  - containerfile: "Containerfile"
    output-name: "{{ $output_name }}"

    build-args:
      BASE_IMAGE: "{{ $image_base }}"

    # {{ $osInfo := dict }}
    # {{/* Check if major version is defined */}}
    # {{ if $major_version }}
    #   {{/* If it is defined, use it... */}}
    #   {{ $osInfo = dict "VERSION_ID" $major_version }}
    # {{ else }}
    #   {{/* ... otherwise, we fetch the image base, and parse from os-release */}}
    #   {{ $osInfo = $image_base | osRelease }}
    # {{ end }}
    output-tags:
      - latest
      - "{{ $now }}"
      - "{{ $osInfo.VERSION_ID }}"

      # {{ range $_, $tag := (slice "latest" "stable") }}
      - "{{ $tag }}"
      - "{{ $tag }}-{{ $osInfo.VERSION_ID }}"
      - "{{ $osInfo.VERSION_ID }}-{{ $tag }}"
      - "{{ $osInfo.VERSION_ID }}.{{ $now }}"
      - "{{ $tag }}-{{ $osInfo.VERSION_ID }}"
      - "{{ $tag }}-{{ $osInfo.VERSION_ID }}.{{ $now }}"
      # {{ end }}

      # {{/* Add commit sha if available */}}
      # {{ with $secrets.GITHUB_SHA }}
      - "{{ . }}"
      # {{ end }}

    labels:
      io.artifacthub.package.keywords: bootc,ublue,universal-blue
      io.artifacthub.package.license: Apache-2.0
      org.opencontainers.image.title: "{{ $output_name }}"
      org.opencontainers.image.source: "{{ $repo }}/blob/main/Containerfile"
      org.opencontainers.image.url: "{{ $repo }}"
      org.opencontainers.image.version: "{{ $now }}"
      org.opencontainers.image.vendor: "{{ $owner }}"
