#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

. source.sh

# Steps to run before doing anything
pre_stage_00_dummy() {
    true
}

# Run pre_stages
builtin compgen -A function | while read -r stage; do
    echo "::group::START PRESTAGE ${stage##pre_stage_}"
    eval "$stage" || {
        echo "::warning::Prestage '${stage##pre_stage_}' has failed"
    }
    echo "::endgroup::"
done

old_shopt="$(shopt -p)"
shopt -s nullglob
for file in ./??-*.sh; do
    if [ ! -x "$file" ]; then
        echo "::warning::Build script '$file' is not executable. Skipping..."
    fi
    echo "::group::START $file"
    $file
    echo "::endgroup::"
done

eval "$old_shopt"
