name: Build Image
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: github.com/Zeglius/bootc-dagger/ci@main
          verb: call
          args: --cfg-file=./bootc-ci.yaml --build-context=. run
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
