name: Build Image
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: Call Dagger Function
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: github.com/Zeglius/bootc-dagger/ci@main
          args: run
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
