name: Trigger packit PR builds

on:
  pull_request:
    types: [synchronize]
    paths-ignore: [.github]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Trigger build
        env:
          WOW: ${{ github.ref }}
        run: |
          set -xo pipefail
          gh pr comment --body "$WOW"
