name: Trigger packit PR builds

on:
  pull_request:
    types: [synchronize]
    paths-ignore: [.github]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Trigger build
        env:
          PR: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          set -xo pipefail
          gh pr comment --repo "$GH_REPO" "$PR" --body "wow"
