# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# WARNING: This workflow is meant for emergency use only.
# Under NO CIRCUMSTANCES should this workflow be automatically triggered.
name: Retag image

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  packages: write

on:
  workflow_dispatch:
    inputs:
      old_tag:
        description: "Old tag from which its image will be retagged to latest"
        required: false

jobs:
  retag-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: fetch_old_sha
        name: Fetch previous commit image tag
        run: |
          set -euo pipefail
          old_sha="$(git log --pretty="format:%H" -1 -- Containerfile build_scripts/ bootc-ci.*)"
          echo "old_sha=$old_sha" | tee --append $GITHUB_ENV

      - name: Safeguard wait
        env:
          SLEEP_TIME: "30"
        run: |
          echo "Triggered safeguard."
          echo "You have $SLEEP_TIME seconds to cancel the workflow if you want to cancel retagging."
          sleep $SLEEP_TIME

      - uses: Zeglius/ghcr-oci-retagger@main
        with:
          PREFIX: ghcr.io/zeglius/
          TAG_MAPPINGS: >-
            mybazzite:${{ inputs.old_tag != '' && inputs.old_tag || env.old_sha }} => mybazzite:latest
