# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# WARNING: This workflow is meant for emergency use only.
# Under NO CIRCUMSTANCES should this workflow be automatically triggered.
name: Retag image

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  packages: write

env:
  IMAGES_TO_RETAG: >-
    ghcr.io/zeglius/mybazzite:latest

on:
  workflow_dispatch:
    inputs:
      INPUT_TAG:
        description: Image tag to convert from
        required: true
        default: latest
      OUTPUT_TAGS:
        description: Image tag to convert into
        required: true
        default: latest

jobs:
  retag-image:
    runs-on: ubuntu-latest
    env:
      INPUT_TAG: ${{ inputs.INPUT_TAG }}
      OUTPUT_TAGS: ${{ inputs.OUTPUT_TAGS }}

    steps:
      - name: Safeguard wait
        env:
          SLEEP_TIME: "30"
        run: |
          echo "Triggered safeguard."
          echo "You have $SLEEP_TIME seconds to cancel the workflow if you want to cancel retagging."
          sleep $SLEEP_TIME

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retag image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

        run: .github/workflows/retag.sh
